baseurl = ""
title = "dan menjivar"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
googleAnalytics = "UA-167541172-1"


paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "dan"

[params]
    author = "Daniel Menjivar"
    info = "Full Stack Software Engineer"
    description = "Dan Menjivar's personal website"
    keywords = "blog,developer,personal"
    avatarurl = "/uploads/memoji.png"
    email = "hello@danmenjivar.com"

    favicon_32 = "/favicons/favicon-32x32.png"
    favicon_16 = "/favicons/favicon-16x16.png"

    footercontent = ""

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 1
    url = "https://linkedin.com/in/danmenjivar/"
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 2
    url = "https://github.com/danmenjivar/"
[[params.social]]
    name = "StackOverflow"
    icon = "fab fa-stack-overflow fa-2x"
    weight = 4
    url = "https://stackoverflow.com/users/12110124/dan"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 5
    url = "https://twitter.com/mrlowkeydan"
[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram fa-2x"
    weight = 6
    url = "https://www.instagram.com/_danmenjivar/"


# Menu links
[[menu.main]]
    name = "Portfolio"
    weight = 1
    url  = "/portfolio/"
[[menu.main]]
    name = "Blog"
    weight = 2
    url  = "/posts/"
[[menu.main]]
    name = "About Me"
    weight = 3
    url = "/about/"